import Head from 'next/head';
import { useState } from 'react';
import Header from '../../components/Header/header';
import Main from '../../components/Main/main';
import Footer from '../../components/Footer/footer';
import Cart from '../../components/Cart/Cart';

export default function Home() {
  const [isCartVisible, setIsCartVisible] = useState(false);

  const handleCartClick = () => {
    setIsCartVisible(true);
  };

  const handleCloseCart = () => {
    setIsCartVisible(false);
  };

  return (
    <>
      <Head>
        <title>Starsoft - Darkgame</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Header onCartClick={handleCartClick} />
      <Main />
      <Footer />
      <Cart isVisible={isCartVisible} onClose={handleCloseCart} />
    </>
  );
}
